--- 
title: "SPP 608 Introduction to Statistics 2021"
author: "Viviana Wu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
config:
     output:
      bookdown::html_book:
        theme: paper
      prettydoc::html_pretty:
        html_document:
          highlight: pygments
          theme: cayman
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This site provides the course materials for SPP 608 Introduction to Statistics 2021."

---
# Course Objectives {#intro}

 <div align="center"> [Viviana Chiu Sik Wu](https://connectivecommons.cc/), PhD, MS, LLB </div>  

 <div align="center">School of Public Policy</div>   

 <div align="center">The University of Massachusetts Amherst</div>  

***


This is an introductory statistical course designed for public policy students to analyze and solve statistical problems in the real world. The goal of this course is to familiarize students with a number of statistical techniques commonly used for analyzing different types of policy data. Throughout the course, it emphasizes two crucial aspects of students’ learning: 1) statistical analysis for policy data, and 2) presentation and interpretation of statistical results. While the course will cover some basic theory behind the majority of the statistical methods, it will focus mostly on their applications. Students will learn when each statistical test should be used and the assumptions behind each test. In addition, students will learn how to describe and interpret the output of the analyses that they run.  The free R open source software will be used for this course for conducting statistical analysis and data visualization. 


**Overview of Class Design** 

This class will have a combination of asynchronous lectures and synchronous discussion and R simulations which will be pre-recorded. In the synchronous session, we will tentatively meet every Thursday at 5:30 pm to do a quick overview of lectures, work through R and review lab assignments in real time. There will be weekly lab assignments. Students will partner up and work on a data analysis project throughout the semester. Methods covered in this course include exploratory data analysis, correlation and bivariate analysis, linear regression, panel data regression, and probit/logistic regression. Collective and reflective learning will be the key cornerstone for excelling in this class! 

**Special Note about Learning in a Pandemic** 

>I am committed to ensuring your successful learning in this class. Please talk to me and ask questions during or after class time. I commit to being thoughtful and empathetic towards each of you as you navigate the current circumstances and your personal situations. I will also be open, fair, professional, and passionate in teaching this class. In turn, I ask that you exercise the same consideration and compassion towards your classmates, TAs and GAs, UMass Amherst staff, and your professors. We are all moving through this differently, but together.

**Course Values**  

* *Empathy*: Care and respect for each other and be empathetic and compassionate. 
* *Openness*: Be proactive to ask questions. Be willing to learn by trial and error. 
* *Integrity*: Take responsibilities for your own and team work. Be fair and trustworthy. 
* *Professionalism*: Have high standards and solid preparation for the class and the team. 
* *Perseverance and passion*: Actively engage and participate to strive for your own learning goals. 

***

**Required Software** 

*Installing R & R Studio* 

You will need to install R (the free and open source statistical computing language used in this course) and R Studio (the graphical user interface for R) in advance before the first class.  

*	Install [R software](https://cran.rstudio.com/)  
*	Install [R Studio Desktop](https://cran.rstudio.com/)  
*	Join the class space on R Studio Cloud [Invited Only]  

There are infinitely many new packages available for us to use. It is highly recommended to use the free RStudio, an interface for writing R documents and working with data. For this class, you will have access to RStudio Cloud where you can use R online anywhere throughout the semester. 

You will also use R Studio Desktop/Cloud to work on your assignment, you will use R Markdown to “knit” your assignment/quiz submission in .docx or .pdf format. All files named: Last name_HW1, e.g., Wu_HW1. More instructions will follow in the first few labs. 

***


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

```
