# Course Expectation {#expect}

**How to be Successful in the Course?** 

In general, any submitted work written work (quizzes and final project) is assessed on these evaluative criteria: 

*	**Thoroughness** – each question is addressed and well-explained 

*	**Rigorous analysis** – analytically rigorous in tackling the assignment 

*	**Professional presentation** – explain codes with notes, accurate interpretation of results 

*	**Problem-solving acumen** – show accumulated learning to approach statistical problems 

***

**Calculation of Grades** 

Student performance in the course will be graded based on the following scale: 

 Grade | Performance 
:----:| :-------:
    A  |  92-100% 
    A- |  90-91%  
    B+ |  88-89% 	
    B  |  82-87% 
    B- |  80-81% 
    C+ |  78-79% 
    C  |  70-77% 
    F  |  69% or below 

## Assignments and Gradings {#hw}

Your grade for this course will be determined by the following:   

*	Assignments 20%
*	Quizzes 40%
*	Final project 40% 


**Assignments**  
There will be six assignments in this course, each due on Wednesday before the next Thursday lab session. You are encouraged to help each other figure out the answers to the problem sets, but it is expected that you write up your answers independently.  

Once the assignments are submitted on GradeScope, students will be given a detailed answer key to grade their assignments and make corrections and notes to explain each error made by the following Tuesday. The TA and I will re-check all self-graded assignments afterward. No matter the score it actually receives, each self-graded assignment will get a full score for the assignment. An assignment not self-graded then will get zero points. In other words, careful work with self-reflection will be counted.   

The whole point of self-grading is to foster reflective and intentional learning—to give you a safe space to reflect on your learning and identify mistakes shortly after making them and revise as needed. The process empowers students to learn effectively and take the initiative in their learning.  

**Quizzes**  
Additionally, there will be two take-home quizzes – covering the first-half and second halves of the course, respectively. You are expected to work on take-home quizzes without the assistance of any other person. You may, however, consult any textbook or internet-resources.  

Students will receive a detailed answer key to self-grade the quizzes, and the instructor will re-check and adjust the grades if needed. While the quizzes will not be adjusted for self-reflection and correction, they have extra credit questions for students to get bonus points.  

**Policy Research Report (Team project)**  
The final project is designed so that each of you will bring a problem of personal interest to the class. You will need to identify a problem to tackle with a data set that either you collect/extract or find. This project team involves a group of up to 3 members. A complete write up is required. This would be a good project to put in your CV if desired.  

*	A well-motivated, relevant topic is most desirable.
*	Originality, complexity, and challenge will be another plus.
*	A complete, professional write up is a must.
*	Maximum of 15 double-spaced pages, in APA 7th format. 
*	IPUMS, Google Dataset, Kaggle are some good places to find a data set.  

**A monthly team check-in with the professor is highly recommended to meet the monthly goal.** 
The final project will be accompanied by a rubric describing the allocation of points and criteria for evaluation. Each group will have a chance to review and provide feedback on the presentation and report from another group. The instructor will grade the final project. The final grade of the course will be adjusted for peer evaluation from your teammates. 

## Course Schedule {#class_schedule}

Methods covered in this course include exploratory data analysis, correlation and bivariate analysis, linear regression, panel data regression, and probit/logistic regression. Collective and reflective learning will be the key cornerstone for excelling in this class! 

| Class Schedule (*Tentative and subject to change*) |
|--- |
| **Week 1, 4-Feb	Course Overview, introduction to Statistics**  |
| Course expectation and plan for success!   | 
| Recognize the different types of data and research questions  | 
| Lab 1	Create your first R markdown	 | 
| **Week 2, 11-Feb	Assumptions of statistical inference**  | 
| Random variables, probability distribution, central limit theorem	 | 
| Assumptions of statistical inference (larger sample size!)  | 
| Use R to graph and explain descriptive statistics of variables  | 
| Lab 2	Exploratory data analysis	| 
| **Week 3, 18-Feb	Hypothesis testing, significance level, t-statistics** | 
| Write hypotheses and interpret statistical results  | 
| Estimate the causal effects of experiments using differences of means  | 
| Lab 3	Compute t-test, ANOVA test, construct confidence interval for treatment effect  | 
| **Week 4, 25-Feb	Simple Linear Regression (Ordinary Least Square (OLS) regression)	**  | 
| Understand Best Linear Unbiased Estimator (BLUE) assumptions  | 
| Interpret and write regression results  | 
| Lab 4	Compute simple regression models 	| 
| **Take home quiz 1 (due Mar 3 at 5pm): Study Week 1 to Week 3**   | 
| **Week 5, 4-Mar	Regression Diagnosis**| 
| Diagnose regression results  | 
| Recognize violation of assumptions  | 
| Lab 5	Run diagnosis plots		| 
| **Week 6, 11-Mar	Multiple Linear Regression, Omitted Variable Bias, Measures of fit** 	| 
| Interpret regression results  | 
| Diagnose model fitness and violation of assumptions  | 
| Lab 6	Compute multiple regression models  | 	
| **Week 7, 18-Mar	Logarithm and Variable Transformation, Binary variables**|  
| Improve model fitness  | 
| Interpret regression results with transformed variable   | 
| Lab 7	Create and plot nonlinear terms	 | 
| **Week 8, 25-Mar	Interaction of independent variables**  	| 
| Improve model fitness | 
| Interpret regression results with interaction terms  | 
| Lab 8	Create and plot interaction terms  | 
| **Week 9, 1-Apr	Regression with Panel Data**   | 
| (control for omitted variables that are constant across cases or time)	| 
| Familiarize panel data structure  | 
| Incorporate fixed effects to models | 
| Lab 9	Fixed effects regression	| 
| **Take home quiz 2 (due Mar 31 at 5pm): Study Week 4 to Week 7**  | 
| **Week 10, 8-Apr	Regression for Binary DV**  | 
| Interpret regression results (ratio)  | 
| Predicted probability   | 
| Lab 10	Run and plot Probit and logistic regression	 | 
| **Week 11, 15-Apr	Course Review	**|   
| Group Check-in with Viviana 	| 
| **Week 12, 22-Apr	Project Presentation** | 
| **Week 13, 29-Apr	Project Presentation** | 
| Final project Report due on May 7th Friday by 11:59 PM  | 
	

## Assignment Schedule {#hw_schedule}

There will be weekly lab assignments. Students will partner up and work on a data analysis project throughout the semester. Submit your assignments and quizzes via [**Gradescope**](https://www.gradescope.com/login). You should submit 2 copies: 1 for self-grading, 1 for official grading. 

*Assignments and Quizzes*  

| Assignments/Quizzes  | Submission Due at 5pm  | Self-grading Due at 5pm  | 
| :--------:|:-------------------------:|:------------------------:| 
| Lab 1 HW  |	Wed 2/10                  | Tue 2/16 | 
| Lab 2 HW  |	Wed 2/17                  | Tue 2/23 | 
| Lab 3 HW  |	Wed 2/24                  | Tue 3/2 | 
| Quiz 1    |	Wed 3/3                   | Tue 3/9 | 
| Lab 5 HW  |	Wed 3/10                  |	Tue 3/16 | 
| Lab 6 HW  |	Wed 3/17                  |	Tue 3/23 | 
| Lab 7 HW  |	Wed 3/24                  |	Tue 3/30 | 
| Quiz 2    |	Wed 3/31                  |	Tue 4/6 | 
  
*Policy Research Report*  

|      February 2021    |	   March 2021   	| April 2021                | 
| :--------------------:|:-----------------:|:------------------------: | 
| Research Question	    | Select data set(s)|	Interpretation of results | 
| Variable measures 	  | Data cleaning	    | Report write-up | 
| Statistical method(s) |	Data analysis     |	Class presentation | 





